name: Release B

on:
  push:
    branches:
    - main
    paths:
    - 'b/**'
  workflow_dispatch:
    inputs:
      draft:
        default: 'false'
        description: 'Is this a draft release?'
        required: false
      prerelease:
        default: 'false'
        description: 'Is this a prerelease?'
        required: false

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SERVICE_NAME: "@monorepo/b"

jobs:
  release-b:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Create release
      id: create-release
      uses: ./.github/actions/create-release
      with:
        draft: ${{ github.event.inputs.draft || false }}
        prerelease: ${{ github.event.inputs.prerelease || false }}
